version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./server:/usr/src/server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./client:/usr/src/client
    ports:
      - "4000:4000"
    env_file:
      - ./client/.env
